### PR TITLE
Support market prioritization fee

### PR DESCRIPTION
**Pull request by michael-lcs**
## Description
Support market prioritization fee in Terminal

### UI Update

Screenshot 2024-01-21 at 11 57 43 PM

### POST /swap payload update
Screenshot 2024-01-21 at 11 59 29 PM

### CODE REVIEW

**Comment by dicksonpys** [comment]
Let's have slightly more margin-top mt-1 or mt-2 is enough
image

**Comment by dicksonpys** [comment]
https://github.com/jup-ag/terminal/assets/34560707/a22f1fc6-9c39-4cde-9187-a2d9a5357246

the button "jumps" a little when being clicked, can you set `border-transparent` as the non-active state, so it will keep occupy the space and won't jump?

**Comment by dicksonpys** [comment]
I think there's several things we need to do to make the experience better.
- Similar to production site, I think we can drop the `Jupiter` on header
- and drop the shortened address on the Wallet
image

- We should have a priority fees indicator on the first glance, similar to jup.ag experience
image
- Do take note the value can be "Custom"
image

**Comment by dicksonpys** [comment]
There's a bug for prioritization fee, to repro:
- Open the settings dialog
- select Turbo market fees
- perform swap
- you can see the `/swap` is called with the last "auto / market" instead of Turbo

image

**Comment by michael-lcs** [comment]
> There's a bug for prioritization fee, to repro:
> 
> * Open the settings dialog
> * select Turbo market fees
> * perform 1st swap
> * Then, open settings dialog, set Market fees
> * you can see the `/swap` is called with the "Turbo" instead of "market"
> 
> image

Fixed

**Comment by michael-lcs** [comment]
this is how the each Setting modal and Terminal looks like after update.

### Terminal

Screenshot 2024-01-22 at 11 59 19 PM

### Setting Modals

| Priority | Slippage | General |
|--- | --- | --- | 
|  Screenshot 2024-01-22 at 11 54 21 PM | Screenshot 2024-01-22 at 11 54 26 PM | Screenshot 2024-01-22 at 11 54 32 PM. |

**Comment by dicksonpys** [comment]
Hey 👋 
Thank you for contributing, we'll take into `prioritization-fee` branch, and take over from there!

**Pull request merged**
