### PR TITLE
Deleted 716MB of Unused Old Compiled Trash Code

### PR DESCRIPTION
**Pull request by thedotmack**
This public folder has every compiled tailwind js McEverythingBurger deluxe, and there's no reason for it to be here. Maybe it should have been .gitignore(d) and maybe the build process needs fixing, or it could just be terrible long term maintenance of the repo. In any event, here be deletions.

### CODE REVIEW

**Comment by thedotmack** [comment]
I did not mean to "deploy" the script did that, but would like someone on the team to review if possible. Thanks!

**Comment by worlddlckgh** [comment]
Unfortunately this `McEverythingBurger deluxe` 😅 is the source.
We run a CF in front of this, and we are required to maintain them, so it doesn't break any existing partner.

`.gitignore` could work, or we could migrate to something else.

**Comment by thedotmack** [comment]
if adding it to .gitignore works, then do that – they don't need to be built in the repo, do they?

**Comment by worlddlckgh** [comment]
> if adding it to .gitignore works, then do that – they don't need to be built in the repo, do they?

we're using NextJS, and the public folder to serve these contents
then cloudflare in front.
so they will have to exist in the repo

**Pull request closed without merging**
